Initial layout
limavfabio/capstone-react pull request #1
Opened 2022-10-06 20:07 UTC by limavfabio

This PR adds the initial implementation of the React Capstone Project, Fruity Vice. It's a web app for viewing information about diverse fruits. Built using React, React Router and Redux.

2022-10-06 22:41 UTC, Whoistolu requested changes
Hi @limavfabio 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._
- #### I will leave these comments here because they are not in your files changes.
- [ ] [REQUIRED] Kindly add a Filter stateless component to filter data retrieved from the API as stated by the project requirement.
- [ ] [REQUIRED] Kindly ensure that this App has unit tests for several components of the app and some pure functions in Redux code and also the App has integration tests using React Testing Library.

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### N/A

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-06 22:41 UTC, Whoistolu commented on README.md
> +# Fruity App
- [x] [REQUIRED] Great job so far @limavfabio 👍🏽 . However, I would recommend that you 

1. Record a video presenting the features of the project
2. The maximum length of the video is 5 minutes
3. The video contains a clear and objective description of the project. The topic and purpose of the project are made clear.
4. The video contains a project demo, highlighting all the project features.
5. The video contains a highlight of a piece of code that you are proud of making.

- [x] [REQUIRED] Kindly add an "Acknowledgements" section that gives appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the author of the [original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).




These recommendations are part of the project requirement and will make your project more professional.

2022-10-06 22:41 UTC, Whoistolu commented on README.md
> +# Live Demo
- [x] [REQUIRED] It is also part of the project requirements that you deploy the application using Heroku, Netlify, or GitHub Pages. kindly ensure that the project is deployed correctly, the home and detail page works as expected. Then attach a link to the deployed project to this part of the README.

2022-10-06 22:41 UTC, Whoistolu commented on src/app/store.js
> +    getDefaultMiddleware().concat(fruitsApiSlice.middleware),
- [ ] [REQUIRED] Kindly ensure that this project uses Redux for state management and data retrieved from the API are stored in the Redux store correctly. This is a hard requirement.

2022-10-06 22:41 UTC, Whoistolu commented on src/routes/FruitDetails.jsx
> +          </div>
- [ ] [REQUIRED] Kindly note that the project requirement states that you should select one main color for the app and be consistent. Kindly remove this color #bde0fe and replace it with a shade of the major color you chose just like you did on the `Home` page.

Your Implementation   |  Figma Design
:-------------------------:|:-------------------------:
![Screenshot from 2022-10-06 23-15-10](https://user-images.githubusercontent.com/58692590/194429712-f935895a-fe2d-47f2-9fea-5a88b2ba1d7f.png) | ![Screenshot from 2022-10-06 23-14-51](https://user-images.githubusercontent.com/58692590/194429866-eb3e3bb1-0f0d-4fa7-bd25-a7e657f0253b.png)

2022-10-06 22:41 UTC, Whoistolu commented on src/components/Header.jsx
> +      </button>
- [ ] [REQUIRED] Kindly ensure that the `Back` button is not been displayed on the `Home` page for a better UI.

2022-10-08 21:32 UTC, codepantha requested changes
# REQUIRES CHANGES ♻️ 

## Hi @limavfabio 👋, 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

## Highlights 🎯 
✔️ Descriptive PR
✔️ Used correct GitFlow
✔️ No linter errors

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-08 21:32 UTC, codepantha commented on README.md
> +# Live Demo
- [ ] As requested by the previous reviewer, please ensure to deploy your application using Heroku, Netlify, or GitHub Pages. kindly ensure that the project is deployed correctly, the home and detail page works as expected. Then attach a link to the deployed project to this part of the README

2022-10-11 16:20 UTC, youmari approved these changes
Hi @limavfabio , 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/xT8qBepJQzUjXpeWU8/giphy.gif)
Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-10-11 17:55 UTC, merged